ecom/urls.py
from django.urls import path
from django.contrib.auth import views
from django import views
from . import views
from django.views.generic import ListView,DetailView
from . models import Book
from . views import all,home,checkout,orders,Contact ,low,high,ItemDetail,product,cart, signup,SearchResultsView,add_to_cart,remove_from_cart

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.all, name='books'),
    path('booklow/', views.low, name='low'),
    path('bookhigh/', views.high, name='high'),

    path('products/', views.product, name='product'),
    path('product/<slug>/', ItemDetail.as_view(),name='product'),

    path('fictionn', ListView.as_view(queryset=Book.objects.filter(category__startswith='Fiction'),template_name="bookcategory.html"), name='fiction'),
    path('fantasy',ListView.as_view(queryset=Book.objects.filter(category__startswith="Fantasy"),template_name="bookcategory.html"),name='fantasy'),
    path('children',ListView.as_view(queryset=Book.objects.filter(category__startswith="Children"),template_name="bookcategory.html"),name='children'),
    path('self-help',ListView.as_view(queryset=Book.objects.filter(category__startswith="Self"),template_name="bookcategory.html"),name='self'),
    path('textbook',ListView.as_view(queryset=Book.objects.filter(category__startswith="Textbook"),template_name="bookcategory.html"),name='textbook'),

    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('contact/', Contact.as_view(), name='contact'),

    path('signup/', views.signup, name='signup'),

    path('cart/', views.cart,name='cart'),
    path('cart/<int:id>/', views.remove_from_cart, name='removefromcart'),
    path('cart/<slug>/', views.add_to_cart,name='updatecart'),
    path('checkout/', views.checkout,name='checkout'),
    path('orders/', views.orders,name='user_orders'),





]

project5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Author(models.Model):
    author_id = models.IntegerField()
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Book(models.Model):
    book_id = models.IntegerField()
    title = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.CharField(max_length=30)
    price = models.IntegerField()
    slug = models.SlugField(null=True, blank=True,unique=True)
    new = models.BooleanField(default=False)
    hot = models.BooleanField(default=False)
    book_img = models.ImageField(upload_to="coverpages/")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product", kwargs={'slug': self.slug})

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Book.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['title']


class Cart(models.Model):
    total = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True, null = True, blank = True) # , null = True, blank = True
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return "Cart id : %s" % self.id


class CartItem(models.Model):
    cart = models.ForeignKey(Cart,null=True,blank=True,on_delete=models.CASCADE)
    product = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    line_total = models.IntegerField(default=10)
    timestamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return str(self.cart.id)


STATUS_CHOICES = (
    ("started", "started"),
    ("abandoned", "abandoned"),
    ("finished", "finished"),
)


class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True,null=True)
    sub_total = models.DecimalField(default=10.00, max_digits=1000, decimal_places=2)
    tax_total = models.DecimalField(default=10.00, max_digits=1000, decimal_places=2)
    final_total = models.DecimalField(default=10.00, max_digits=1000, decimal_places=2)
    order_id = models.CharField(max_length=120,default='ABC', unique=True)
    status = models.CharField(max_length=100, choices= STATUS_CHOICES,default="started")
    timestamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.order_id

ecom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.forms import ModelForm


class SignUp(UserCreationForm):
    name = forms.CharField(max_length=40)
    username = forms.CharField(max_length=50)
    email = forms.EmailField()
    phone = forms.IntegerField()
    address = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ["name",'username','password1','password2','phone','email','address']

ecom/views.py
from django.shortcuts import render, redirect, reverse
from django import views
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, FormView, CreateView, TemplateView, DetailView
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from . forms import SignUp
from . models import Book, Cart, CartItem, Order
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from . utils import id_generator
import time
# Create your views here.


def home(request):
    book = Book.objects.all()
    return render(request,'index.html',{'book' : book})


class Contact(TemplateView):
    template_name = 'contact.html'


class SearchResultsView(ListView):
    model = Book
    template_name = 'bookcategory.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Book.objects.filter(
            Q(title__icontains=query) | Q(author__name__icontains=query)
        )
        return object_list


def signup(request):
    if request.method == 'POST':
        form = SignUp(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = SignUp()
    return render(request,"signup.html",{'form':form})


def all(request):
    num = Book.objects.all()
    paginator = Paginator(num, 12)
    page = request.GET.get('page')
    b = paginator.get_page(page)
    return render(request, 'booklist.html', {'item': b})


def low(request):
    sort = Book.objects.all().order_by('price')
    return render(request, 'booklist.html', {'item': sort})


def high(request):
    sort = Book.objects.all().order_by('-price')
    return render(request, 'booklist.html', {'item': sort})


class ItemDetail(DetailView):
    model = Book
    template_name = 'productpage.html'


def product(request):
    book = Book.objects.all()
    return render(request,'product.html',{'book': book})


def add_to_cart(request,slug):
    request.session.set_expiry(14000000)
    try:
        qty = request.GET.get('qty')
        update_qty = True
    except:
        pass
    try:
        the_id = request.session['cartid']
    except:
        new_cart = Cart()
        new_cart.save()
        request.session['cartid'] = new_cart.id
        the_id = new_cart.id

    cart = Cart.objects.get(id=the_id)
    try:
        product = Book.objects.get(slug=slug)
    except Book.DoesNotExist:
        pass

    cart_prod,created = CartItem.objects.get_or_create(cart=cart, product=product)
    cart_prod.quantity = qty
    cart_prod.save()
    return HttpResponseRedirect(reverse('cart'))

def remove_from_cart(request, id):
    try:
        the_id = request.session['cartid']
        cart = Cart.objects.get(id=the_id)
    except:
        return HttpResponseRedirect(reverse('cart'))

    cartitem = CartItem.objects.get(id=id)
    cartitem.delete()
    request.session['items_total'] = cart.cartitem_set.count()
    return HttpResponseRedirect(reverse('cart'))


def cart(request):
    try:
        the_id = request.session['cartid']
    except:
        the_id = None
    if the_id:
        cart = Cart.objects.get(id=the_id)
        # cartitem = CartItem.objects.get(cart=cart)
        # cart_prod, created = CartItem.objects.get_or_create(cart=cart, product=product)
        new_total = 0
        for item in cart.cartitem_set.all():
            line_total = item.product.price * item.quantity
            item.line_total = line_total
            item.save()
            new_total += line_total
        request.session['items_total'] = cart.cartitem_set.count()
        cart.total = new_total
        cart.save()
        context = {'cart': cart}
    else:
        empty_msg = "Your Cart is Empty. Please keep shopping"
        context = {"empty": True, 'empty_msg':empty_msg}
    return render(request,'cart.html',context)


def orders(request):
    context = {}
    return render(request,"user.html",context)


@login_required
def checkout(request):
    try:
        the_id = request.session['cartid']
        cart = Cart.objects.get(id=the_id)
    except Cart.DoesNotExist:
        the_id = None
        return HttpResponseRedirect(reverse("cart"))

    new_order, created = Order.objects.get_or_create(cart=cart)
    if created:
        new_order.order_id = id_generator() #str(time.time())
        new_order.save()
    new_order.user = request.user
    new_order.save()

    if new_order.status == "finished":
        # cart.delete()
        del request.session['cartid']
        del request.session['items_total']

    context = {'cart':cart}
    return render(request, "checkout.html", context)

ecom/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>BookWorm</title>
<meta charset="utf-8">
{% load static %}
{% static "images" as baseUrl %}

{% block script %} {% endblock script %}

</head>
<body>

    <div class="super_container">
        <header class="header">
            <div class="header_container">
                <div class="container">
<!--                    insert-->
                    <div class="row">
                        <div class="col">
                            <div class="header_content d-flex flex-row align-items-center justify-content-start">
                                <div class="logo"><a href="{% url 'home' %}">BOOKWORM</a></div>
                                <nav class="main_nav">
                                    <ul>
                                        <li class="hassubs active">
                                            <a href="{% url 'home' %}">Home</a>
                                            <ul>
                                                <li><a href="{% url 'books' %}">Books</a></li>
                                                <li><a href="{% url 'cart' %}">Cart</a></li>
                                                <li><a href="{% url 'checkout' %}">Checkout</a></li>
                                            </ul>
                                        </li>
                                        <li class="hassubs">
                                            <a href="{% url 'books' %}">Categories</a>
                                            <ul>
                                                <li><a href="{% url 'fiction' %}">Fiction</a></li>
                                                <li><a href="{% url 'fantasy' %}">Fantasy</a></li>
                                                <li><a href="{% url 'children' %}">Children's Books</a></li>
                                                <li><a href="{% url 'self' %}">Self-Help</a></li>
                                                <li><a href="{% url 'textbook' %}">Textbooks</a></li>
                                            </ul>
                                        </li>

                                        <li><a href="{% url 'signup' %}">Sign Up</a></li>


                                        <div class="shopping_cart">
                                            <a href="{% url 'cart' %}">
                                                <div><b>Cart<span><font size="2">(
                                                    {% if not request.session.items_total %}
                                                        0
                                                    {% else %}
                                                        {{ request.session.items_total }}
                                                    {% endif %}
                                                    )</font></span></b>
                                                </div>
                                            </a>
                                        </div>
                                        <div class="search">
                                            <div class="search_icon">
                                                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                                viewBox="0 0 475.084 475.084" style="{% static 'enable-background:new 0 0 475.084 475.084;' %}"
                                                 xml:space="preserve">
                                                <g>
                                                    <path d="M464.524,412.846l-97.929-97.925c23.6-34.068,35.406-72.047,35.406-113.917c0-27.218-5.284-53.249-15.852-78.087
                                                        c-10.561-24.842-24.838-46.254-42.825-64.241c-17.987-17.987-39.396-32.264-64.233-42.826
                                                        C254.246,5.285,228.217,0.003,200.999,0.003c-27.216,0-53.247,5.282-78.085,15.847C98.072,26.412,76.66,40.689,58.673,58.676
                                                        c-17.989,17.987-32.264,39.403-42.827,64.241C5.282,147.758,0,173.786,0,201.004c0,27.216,5.282,53.238,15.846,78.083
                                                        c10.562,24.838,24.838,46.247,42.827,64.234c17.987,17.993,39.403,32.264,64.241,42.832c24.841,10.563,50.869,15.844,78.085,15.844
                                                        c41.879,0,79.852-11.807,113.922-35.405l97.929,97.641c6.852,7.231,15.406,10.849,25.693,10.849
                                                        c9.897,0,18.467-3.617,25.694-10.849c7.23-7.23,10.848-15.796,10.848-25.693C475.088,428.458,471.567,419.889,464.524,412.846z
                                                         M291.363,291.358c-25.029,25.033-55.148,37.549-90.364,37.549c-35.21,0-65.329-12.519-90.36-37.549
                                                        c-25.031-25.029-37.546-55.144-37.546-90.36c0-35.21,12.518-65.334,37.546-90.36c25.026-25.032,55.15-37.546,90.36-37.546
                                                        c35.212,0,65.331,12.519,90.364,37.546c25.033,25.026,37.548,55.15,37.548,90.36C328.911,236.214,316.392,266.329,291.363,291.358z
                                                        "/>
                                                </g>
                                                </svg>
                                            </div>
                                        </div>
                                        <div class="hamburger"><i class="fa fa-bars" aria-hidden="true"></i></div>
                                    </ul>
                                </nav>

                                <div class="header_extra ml-auto">
                                    <div class="row">
                                        <div class="col">
                                            <div class="search_panel_content d-flex flex-row align-items-center justify-content-end">
                                                <div>
                                                    {% if user.is_authenticated %}
                                                        Hi {{ user.username }}! &nbsp;
                                                        <a href="{% url 'logout' %}">Logout</a>
                                                    {% else %}
                                                        <a href="{% url 'login' %}">Login</a>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Search Panel -->
            <div class="search_panel trans_300">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="search_panel_content d-flex flex-row align-items-center justify-content-end">
                                <form action="{% url 'search_results' %}" method="get">
                                    <input type="text" class="search_input" placeholder="Search" name='q' required="required">
                                    <button type="submit" class="btn btn-success">Search</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Social -->
            <div class="header_social">
                <ul>
                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </header>


        {% block content %}
        {% endblock content %}
    </div>

{% block script2 %} {% endblock script2 %}

</body>
</html>

ecom/templates/bookcategory.html
{% extends "base2.html" %}
{% load static %}
{% static "images" as baseUrl %}

{% block script %}
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Sublime project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
	<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/categories.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/categories_responsive.css' %}">
{% endblock script %}

{% block content %}
	<!-- Products -->

	<div class="products">
		<div class="container">

			<div class="row">
				<div class="col">

					<br><br><br><br><br><br><br><br>
<!--					<div class="sorting_bar d-flex flex-md-row flex-column align-items-md-center justify-content-md-start">-->
<!--						<div class="results"><span></span></div>-->
<!--						<div class="sorting_container ml-md-auto">-->
<!--							<div class="sorting">-->
<!--								<ul class="item_sorting">-->
<!--									<li>-->
<!--										<span class="sorting_text">Sort by Price</span>-->
<!--										<i class="fa fa-chevron-down" aria-hidden="true"></i>-->
<!--										<ul>-->
<!--&lt;!&ndash;											<li class="product_sorting_btn" data-isotope-option='{ "sortBy": "original-order" }'><span>Default</span></li>&ndash;&gt;-->
<!--											<li class="product_sorting_btn" data-isotope-option='{ "sortBy": "low" }'><a href="{% url 'low' %}"> <span>Low to High</span></a></li>-->
<!--											<li class="product_sorting_btn" data-isotope-option='{ "sortBy": "high" }'><a href="{% url 'high' %}"> <span>High to Low</span></a></li>-->
<!--										</ul>-->
<!--									</li>-->
<!--								</ul>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->

				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="product_grid">
                        {% for item in object_list %}
                        <div class="product">
                            <div class="product_image"><a href ="{% url 'product' item.slug %}"><img src="{{ item.book_img.url }}" alt="" height="230" width="180"></a></div>
                            {% if item.new %}
								<div class="product_extra product_new"><a href="product">New</a></div>
                            {% endif %}
                            {% if item.hot %}
								<div class="product_extra product_new"><a href="product">Hot</a></div>
                            {% endif %}
								<div class="product_content">
									<div class="product_title"><h6>{{ item.title }} </h6></div>
									<div class="product_price"><h6>Price: {{ item.price }}</h6></div>
								</div>
						</div>
						{% endfor %}
						</div>


					</div>
					<div class="product_pagination">
						<div style="display: flex; justify-content: flex-end">
							<span class="step-links">
								{% if item.has_previous %}
									<a href="?page=1"> First &nbsp; </a>
								<a href="?page={{ item.previous_page_number }}"> &laquo; Prev &nbsp; </a>
								{% endif %}

								<span class="current">
									Page {{ item.number }} of {{ item.paginator.num_pages }} &nbsp;
								</span>

								{% if item.has_next %}
									<a href="?page={{ item.next_page_number }}"> Next &nbsp;</a>
									<a href="?page={{ item.paginator.num_pages }}"> Last &raquo;</a>
								{% endif %}
							</span>
						</div>
					<div><br><br></div>
					</div>

				</div>
			</div>
		</div>

	<!-- Footer -->

	<div class="footer_overlay"></div>
	<footer class="footer">
		<div class="footer_background" style="background-image:url('/static/images/footer.jpg')"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="footer_content d-flex flex-lg-row flex-column align-items-center justify-content-lg-start justify-content-center">
						<div class="footer_logo"><a href="#"></a></div>

						<div class="footer_social ml-lg-auto">
							<ul>
								<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

{% endblock content %}
{% block script2 %}
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
	<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
	<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
	<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
	<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
	<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
	<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
	<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
	<script src="{% static 'plugins/Isotope/isotope.pkgd.min.js' %}"></script>
	<script src="{% static 'plugins/easing/easing.js' %}"></script>
	<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
	<script src="{% static 'js/categories.js' %}"></script>
{% endblock script2 %}

ecom/templates/booklist.html
{% extends "base2.html" %}
{% load static %}
{% static "images" as baseUrl %}

{% block script %}
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Sublime project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
	<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/categories.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/categories_responsive.css' %}">
{% endblock script %}


{% block content %}
	<div class="products">
		<div class="container">

			<div class="row">
				<div class="col">
					<br><br><br><br>
					<div class="sorting_bar d-flex flex-md-row flex-column align-items-md-center justify-content-md-start">
						<div class="results"><span></span></div>
						<div class="sorting_container ml-md-auto">
							<div class="sorting">
								<ul class="item_sorting">
									<li>
										<span class="sorting_text">Sort by Price</span>
										<i class="fa fa-chevron-down" aria-hidden="true"></i>
										<ul>
<!--											<li class="product_sorting_btn" data-isotope-option='{ "sortBy": "original-order" }'><span>Default</span></li>-->
											<li class="product_sorting_btn" data-isotope-option='{ "sortBy": "low" }'><a href="{% url 'low' %}"> <span>Low to High</span></a></li>
											<li class="product_sorting_btn" data-isotope-option='{ "sortBy": "high" }'><a href="{% url 'high' %}"> <span>High to Low</span></a></li>
										</ul>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="product_grid">
						<!-- Product -->
						{% for item in item %}
						<div class="product">
								<div class="product_image"><a href ="{% url 'product' item.slug %}"><img src="{{ item.book_img.url }}" alt="" height="230" width="180"></a></div>
								{% if item.new %}
									<div class="product_extra product_new"><a href="product">New</a></div>
								{% endif %}
								{% if item.hot %}
									<div class="product_extra product_new"><a href="product">Hot</a></div>
								{% endif %}
								<div class="product_content">
									<div class="product_title"><h6>{{ item.title }} </h6></div>
									<div class="product_price"><h6>Price: {{ item.price }}</h6></div>
								</div>
						</div>
						{% endfor %}
					</div>
					<div style="display: flex; justify-content: flex-end">
							<span class="step-links">
								{% if item.has_previous %}
									<a href="?page=1"> First &nbsp; </a>
								<a href="?page={{ item.previous_page_number }}"> &laquo; Prev &nbsp; </a>
								{% endif %}

								<span class="current">
									Page {{ item.number }} of {{ item.paginator.num_pages }} &nbsp;
								</span>

								{% if item.has_next %}
									<a href="?page={{ item.next_page_number }}"> Next &nbsp;</a>
									<a href="?page={{ item.paginator.num_pages }}"> Last &raquo;</a>
								{% endif %}
							</span>
						</div>
					<div><br><br></div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

{% block script2 %}
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
	<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
	<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
	<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
	<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
	<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
	<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
	<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
	<script src="{% static 'plugins/Isotope/isotope.pkgd.min.js' %}"></script>
	<script src="{% static 'plugins/easing/easing.js' %}"></script>
	<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
	<script src="{% static 'js/categories.js' %}"></script>
{% endblock script2 %}

ecom/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for book in object_list %}
        {{ book.category }}
    {% endfor %}
</body>
</html>

ecom/templates/user.html
    {{ user.order_set.all }}